/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: c_service.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "c_service.pb-c.h"
void   cmld_to_service_message__init
                     (CmldToServiceMessage         *message)
{
  static CmldToServiceMessage init_value = CMLD_TO_SERVICE_MESSAGE__INIT;
  *message = init_value;
}
size_t cmld_to_service_message__get_packed_size
                     (const CmldToServiceMessage *message)
{
  assert(message->base.descriptor == &cmld_to_service_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cmld_to_service_message__pack
                     (const CmldToServiceMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cmld_to_service_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cmld_to_service_message__pack_to_buffer
                     (const CmldToServiceMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cmld_to_service_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CmldToServiceMessage *
       cmld_to_service_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CmldToServiceMessage *)
     protobuf_c_message_unpack (&cmld_to_service_message__descriptor,
                                allocator, len, data);
}
void   cmld_to_service_message__free_unpacked
                     (CmldToServiceMessage *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &cmld_to_service_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   service_to_cmld_message__init
                     (ServiceToCmldMessage         *message)
{
  static ServiceToCmldMessage init_value = SERVICE_TO_CMLD_MESSAGE__INIT;
  *message = init_value;
}
size_t service_to_cmld_message__get_packed_size
                     (const ServiceToCmldMessage *message)
{
  assert(message->base.descriptor == &service_to_cmld_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t service_to_cmld_message__pack
                     (const ServiceToCmldMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &service_to_cmld_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t service_to_cmld_message__pack_to_buffer
                     (const ServiceToCmldMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &service_to_cmld_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ServiceToCmldMessage *
       service_to_cmld_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ServiceToCmldMessage *)
     protobuf_c_message_unpack (&service_to_cmld_message__descriptor,
                                allocator, len, data);
}
void   service_to_cmld_message__free_unpacked
                     (ServiceToCmldMessage *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &service_to_cmld_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue cmld_to_service_message__code__enum_values_by_number[10] =
{
  { "SHUTDOWN", "CMLD_TO_SERVICE_MESSAGE__CODE__SHUTDOWN", 1 },
  { "SUSPEND", "CMLD_TO_SERVICE_MESSAGE__CODE__SUSPEND", 2 },
  { "RESUME", "CMLD_TO_SERVICE_MESSAGE__CODE__RESUME", 3 },
  { "AUDIO_SUSPEND", "CMLD_TO_SERVICE_MESSAGE__CODE__AUDIO_SUSPEND", 5 },
  { "AUDIO_RESUME", "CMLD_TO_SERVICE_MESSAGE__CODE__AUDIO_RESUME", 6 },
  { "CONNECTIVITY_CHANGE", "CMLD_TO_SERVICE_MESSAGE__CODE__CONNECTIVITY_CHANGE", 14 },
  { "AIRPLANE_MODE_CHANGED", "CMLD_TO_SERVICE_MESSAGE__CODE__AIRPLANE_MODE_CHANGED", 15 },
  { "WIFI_USER_ENABLED_CHANGED", "CMLD_TO_SERVICE_MESSAGE__CODE__WIFI_USER_ENABLED_CHANGED", 16 },
  { "CONTAINER_CFG_NAME", "CMLD_TO_SERVICE_MESSAGE__CODE__CONTAINER_CFG_NAME", 17 },
  { "CONTAINER_CFG_DNS", "CMLD_TO_SERVICE_MESSAGE__CODE__CONTAINER_CFG_DNS", 18 },
};
static const ProtobufCIntRange cmld_to_service_message__code__value_ranges[] = {
{1, 0},{5, 3},{14, 5},{0, 10}
};
static const ProtobufCEnumValueIndex cmld_to_service_message__code__enum_values_by_name[10] =
{
  { "AIRPLANE_MODE_CHANGED", 6 },
  { "AUDIO_RESUME", 4 },
  { "AUDIO_SUSPEND", 3 },
  { "CONNECTIVITY_CHANGE", 5 },
  { "CONTAINER_CFG_DNS", 9 },
  { "CONTAINER_CFG_NAME", 8 },
  { "RESUME", 2 },
  { "SHUTDOWN", 0 },
  { "SUSPEND", 1 },
  { "WIFI_USER_ENABLED_CHANGED", 7 },
};
const ProtobufCEnumDescriptor cmld_to_service_message__code__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "CmldToServiceMessage.Code",
  "Code",
  "CmldToServiceMessage__Code",
  "",
  10,
  cmld_to_service_message__code__enum_values_by_number,
  10,
  cmld_to_service_message__code__enum_values_by_name,
  3,
  cmld_to_service_message__code__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ContainerConnectivity cmld_to_service_message__connectivity__default_value = CONTAINER_CONNECTIVITY__OFFLINE;
static const ProtobufCFieldDescriptor cmld_to_service_message__field_descriptors[8] =
{
  {
    "code",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(CmldToServiceMessage, code),
    &cmld_to_service_message__code__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "connectivity",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(CmldToServiceMessage, has_connectivity),
    offsetof(CmldToServiceMessage, connectivity),
    &container_connectivity__descriptor,
    &cmld_to_service_message__connectivity__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "source_id",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CmldToServiceMessage, source_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "source_color",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CmldToServiceMessage, source_color),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "airplane_mode",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(CmldToServiceMessage, has_airplane_mode),
    offsetof(CmldToServiceMessage, airplane_mode),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wifi_user_enabled",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(CmldToServiceMessage, has_wifi_user_enabled),
    offsetof(CmldToServiceMessage, wifi_user_enabled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "container_cfg_name",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CmldToServiceMessage, container_cfg_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "container_cfg_dns",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CmldToServiceMessage, container_cfg_dns),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cmld_to_service_message__field_indices_by_name[] = {
  4,   /* field[4] = airplane_mode */
  0,   /* field[0] = code */
  1,   /* field[1] = connectivity */
  7,   /* field[7] = container_cfg_dns */
  6,   /* field[6] = container_cfg_name */
  3,   /* field[3] = source_color */
  2,   /* field[2] = source_id */
  5,   /* field[5] = wifi_user_enabled */
};
static const ProtobufCIntRange cmld_to_service_message__number_ranges[4 + 1] =
{
  { 1, 0 },
  { 6, 1 },
  { 8, 2 },
  { 11, 4 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor cmld_to_service_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CmldToServiceMessage",
  "CmldToServiceMessage",
  "CmldToServiceMessage",
  "",
  sizeof(CmldToServiceMessage),
  8,
  cmld_to_service_message__field_descriptors,
  cmld_to_service_message__field_indices_by_name,
  4,  cmld_to_service_message__number_ranges,
  (ProtobufCMessageInit) cmld_to_service_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue service_to_cmld_message__code__enum_values_by_number[16] =
{
  { "BOOT_COMPLETED", "SERVICE_TO_CMLD_MESSAGE__CODE__BOOT_COMPLETED", 1 },
  { "SUSPEND_COMPLETED", "SERVICE_TO_CMLD_MESSAGE__CODE__SUSPEND_COMPLETED", 2 },
  { "RESUME_COMPLETED", "SERVICE_TO_CMLD_MESSAGE__CODE__RESUME_COMPLETED", 3 },
  { "AUDIO_SUSPEND_COMPLETED", "SERVICE_TO_CMLD_MESSAGE__CODE__AUDIO_SUSPEND_COMPLETED", 5 },
  { "AUDIO_RESUME_COMPLETED", "SERVICE_TO_CMLD_MESSAGE__CODE__AUDIO_RESUME_COMPLETED", 6 },
  { "CALL_ACTIVE", "SERVICE_TO_CMLD_MESSAGE__CODE__CALL_ACTIVE", 7 },
  { "CALL_HANGUP", "SERVICE_TO_CMLD_MESSAGE__CODE__CALL_HANGUP", 8 },
  { "SHUTDOWN", "SERVICE_TO_CMLD_MESSAGE__CODE__SHUTDOWN", 10 },
  { "MASTER_CLEAR", "SERVICE_TO_CMLD_MESSAGE__CODE__MASTER_CLEAR", 11 },
  { "SWITCH_CONTAINER", "SERVICE_TO_CMLD_MESSAGE__CODE__SWITCH_CONTAINER", 13 },
  { "CONNECTIVITY_CHANGE", "SERVICE_TO_CMLD_MESSAGE__CODE__CONNECTIVITY_CHANGE", 14 },
  { "IMEI_MAC_PHONENO", "SERVICE_TO_CMLD_MESSAGE__CODE__IMEI_MAC_PHONENO", 15 },
  { "AIRPLANE_MODE_CHANGED", "SERVICE_TO_CMLD_MESSAGE__CODE__AIRPLANE_MODE_CHANGED", 16 },
  { "WIFI_USER_ENABLED_CHANGED", "SERVICE_TO_CMLD_MESSAGE__CODE__WIFI_USER_ENABLED_CHANGED", 17 },
  { "CONTAINER_CFG_NAME_REQ", "SERVICE_TO_CMLD_MESSAGE__CODE__CONTAINER_CFG_NAME_REQ", 18 },
  { "CONTAINER_CFG_DNS_REQ", "SERVICE_TO_CMLD_MESSAGE__CODE__CONTAINER_CFG_DNS_REQ", 19 },
};
static const ProtobufCIntRange service_to_cmld_message__code__value_ranges[] = {
{1, 0},{5, 3},{10, 7},{13, 9},{0, 16}
};
static const ProtobufCEnumValueIndex service_to_cmld_message__code__enum_values_by_name[16] =
{
  { "AIRPLANE_MODE_CHANGED", 12 },
  { "AUDIO_RESUME_COMPLETED", 4 },
  { "AUDIO_SUSPEND_COMPLETED", 3 },
  { "BOOT_COMPLETED", 0 },
  { "CALL_ACTIVE", 5 },
  { "CALL_HANGUP", 6 },
  { "CONNECTIVITY_CHANGE", 10 },
  { "CONTAINER_CFG_DNS_REQ", 15 },
  { "CONTAINER_CFG_NAME_REQ", 14 },
  { "IMEI_MAC_PHONENO", 11 },
  { "MASTER_CLEAR", 8 },
  { "RESUME_COMPLETED", 2 },
  { "SHUTDOWN", 7 },
  { "SUSPEND_COMPLETED", 1 },
  { "SWITCH_CONTAINER", 9 },
  { "WIFI_USER_ENABLED_CHANGED", 13 },
};
const ProtobufCEnumDescriptor service_to_cmld_message__code__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ServiceToCmldMessage.Code",
  "Code",
  "ServiceToCmldMessage__Code",
  "",
  16,
  service_to_cmld_message__code__enum_values_by_number,
  16,
  service_to_cmld_message__code__enum_values_by_name,
  4,
  service_to_cmld_message__code__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ContainerConnectivity service_to_cmld_message__connectivity__default_value = CONTAINER_CONNECTIVITY__OFFLINE;
static const ProtobufCFieldDescriptor service_to_cmld_message__field_descriptors[8] =
{
  {
    "code",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(ServiceToCmldMessage, code),
    &service_to_cmld_message__code__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "connectivity",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(ServiceToCmldMessage, has_connectivity),
    offsetof(ServiceToCmldMessage, connectivity),
    &container_connectivity__descriptor,
    &service_to_cmld_message__connectivity__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "imei",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ServiceToCmldMessage, imei),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mac",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ServiceToCmldMessage, mac),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "phonenumber",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ServiceToCmldMessage, phonenumber),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "airplane_mode",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(ServiceToCmldMessage, has_airplane_mode),
    offsetof(ServiceToCmldMessage, airplane_mode),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "target_container",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ServiceToCmldMessage, target_container),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wifi_user_enabled",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(ServiceToCmldMessage, has_wifi_user_enabled),
    offsetof(ServiceToCmldMessage, wifi_user_enabled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned service_to_cmld_message__field_indices_by_name[] = {
  5,   /* field[5] = airplane_mode */
  0,   /* field[0] = code */
  1,   /* field[1] = connectivity */
  2,   /* field[2] = imei */
  3,   /* field[3] = mac */
  4,   /* field[4] = phonenumber */
  6,   /* field[6] = target_container */
  7,   /* field[7] = wifi_user_enabled */
};
static const ProtobufCIntRange service_to_cmld_message__number_ranges[4 + 1] =
{
  { 1, 0 },
  { 6, 1 },
  { 8, 2 },
  { 13, 6 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor service_to_cmld_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ServiceToCmldMessage",
  "ServiceToCmldMessage",
  "ServiceToCmldMessage",
  "",
  sizeof(ServiceToCmldMessage),
  8,
  service_to_cmld_message__field_descriptors,
  service_to_cmld_message__field_indices_by_name,
  4,  service_to_cmld_message__number_ranges,
  (ProtobufCMessageInit) service_to_cmld_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
