/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: control.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "control.pb-c.h"
void   container_start_params__init
                     (ContainerStartParams         *message)
{
  static ContainerStartParams init_value = CONTAINER_START_PARAMS__INIT;
  *message = init_value;
}
size_t container_start_params__get_packed_size
                     (const ContainerStartParams *message)
{
  assert(message->base.descriptor == &container_start_params__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t container_start_params__pack
                     (const ContainerStartParams *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &container_start_params__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t container_start_params__pack_to_buffer
                     (const ContainerStartParams *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &container_start_params__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ContainerStartParams *
       container_start_params__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ContainerStartParams *)
     protobuf_c_message_unpack (&container_start_params__descriptor,
                                allocator, len, data);
}
void   container_start_params__free_unpacked
                     (ContainerStartParams *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &container_start_params__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   assign_interface_params__init
                     (AssignInterfaceParams         *message)
{
  static AssignInterfaceParams init_value = ASSIGN_INTERFACE_PARAMS__INIT;
  *message = init_value;
}
size_t assign_interface_params__get_packed_size
                     (const AssignInterfaceParams *message)
{
  assert(message->base.descriptor == &assign_interface_params__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t assign_interface_params__pack
                     (const AssignInterfaceParams *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &assign_interface_params__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t assign_interface_params__pack_to_buffer
                     (const AssignInterfaceParams *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &assign_interface_params__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AssignInterfaceParams *
       assign_interface_params__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AssignInterfaceParams *)
     protobuf_c_message_unpack (&assign_interface_params__descriptor,
                                allocator, len, data);
}
void   assign_interface_params__free_unpacked
                     (AssignInterfaceParams *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &assign_interface_params__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   controller_to_daemon__init
                     (ControllerToDaemon         *message)
{
  static ControllerToDaemon init_value = CONTROLLER_TO_DAEMON__INIT;
  *message = init_value;
}
size_t controller_to_daemon__get_packed_size
                     (const ControllerToDaemon *message)
{
  assert(message->base.descriptor == &controller_to_daemon__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t controller_to_daemon__pack
                     (const ControllerToDaemon *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &controller_to_daemon__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t controller_to_daemon__pack_to_buffer
                     (const ControllerToDaemon *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &controller_to_daemon__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ControllerToDaemon *
       controller_to_daemon__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ControllerToDaemon *)
     protobuf_c_message_unpack (&controller_to_daemon__descriptor,
                                allocator, len, data);
}
void   controller_to_daemon__free_unpacked
                     (ControllerToDaemon *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &controller_to_daemon__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   daemon_to_controller__init
                     (DaemonToController         *message)
{
  static DaemonToController init_value = DAEMON_TO_CONTROLLER__INIT;
  *message = init_value;
}
size_t daemon_to_controller__get_packed_size
                     (const DaemonToController *message)
{
  assert(message->base.descriptor == &daemon_to_controller__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t daemon_to_controller__pack
                     (const DaemonToController *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &daemon_to_controller__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t daemon_to_controller__pack_to_buffer
                     (const DaemonToController *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &daemon_to_controller__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DaemonToController *
       daemon_to_controller__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DaemonToController *)
     protobuf_c_message_unpack (&daemon_to_controller__descriptor,
                                allocator, len, data);
}
void   daemon_to_controller__free_unpacked
                     (DaemonToController *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &daemon_to_controller__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   daemon_to_console__init
                     (DaemonToConsole         *message)
{
  static DaemonToConsole init_value = DAEMON_TO_CONSOLE__INIT;
  *message = init_value;
}
size_t daemon_to_console__get_packed_size
                     (const DaemonToConsole *message)
{
  assert(message->base.descriptor == &daemon_to_console__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t daemon_to_console__pack
                     (const DaemonToConsole *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &daemon_to_console__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t daemon_to_console__pack_to_buffer
                     (const DaemonToConsole *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &daemon_to_console__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DaemonToConsole *
       daemon_to_console__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DaemonToConsole *)
     protobuf_c_message_unpack (&daemon_to_console__descriptor,
                                allocator, len, data);
}
void   daemon_to_console__free_unpacked
                     (DaemonToConsole *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &daemon_to_console__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   console_to_daemon__init
                     (ConsoleToDaemon         *message)
{
  static ConsoleToDaemon init_value = CONSOLE_TO_DAEMON__INIT;
  *message = init_value;
}
size_t console_to_daemon__get_packed_size
                     (const ConsoleToDaemon *message)
{
  assert(message->base.descriptor == &console_to_daemon__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t console_to_daemon__pack
                     (const ConsoleToDaemon *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &console_to_daemon__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t console_to_daemon__pack_to_buffer
                     (const ConsoleToDaemon *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &console_to_daemon__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ConsoleToDaemon *
       console_to_daemon__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ConsoleToDaemon *)
     protobuf_c_message_unpack (&console_to_daemon__descriptor,
                                allocator, len, data);
}
void   console_to_daemon__free_unpacked
                     (ConsoleToDaemon *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &console_to_daemon__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
char container_start_params__key__default_value[] = "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
static const protobuf_c_boolean container_start_params__no_switch__default_value = 0;
static const protobuf_c_boolean container_start_params__setup__default_value = 0;
static const ProtobufCFieldDescriptor container_start_params__field_descriptors[3] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ContainerStartParams, key),
    NULL,
    &container_start_params__key__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "no_switch",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(ContainerStartParams, has_no_switch),
    offsetof(ContainerStartParams, no_switch),
    NULL,
    &container_start_params__no_switch__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "setup",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(ContainerStartParams, has_setup),
    offsetof(ContainerStartParams, setup),
    NULL,
    &container_start_params__setup__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned container_start_params__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = no_switch */
  2,   /* field[2] = setup */
};
static const ProtobufCIntRange container_start_params__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor container_start_params__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ContainerStartParams",
  "ContainerStartParams",
  "ContainerStartParams",
  "",
  sizeof(ContainerStartParams),
  3,
  container_start_params__field_descriptors,
  container_start_params__field_indices_by_name,
  1,  container_start_params__number_ranges,
  (ProtobufCMessageInit) container_start_params__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const protobuf_c_boolean assign_interface_params__persistent__default_value = 0;
static const ProtobufCFieldDescriptor assign_interface_params__field_descriptors[2] =
{
  {
    "iface_name",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AssignInterfaceParams, iface_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "persistent",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(AssignInterfaceParams, has_persistent),
    offsetof(AssignInterfaceParams, persistent),
    NULL,
    &assign_interface_params__persistent__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned assign_interface_params__field_indices_by_name[] = {
  0,   /* field[0] = iface_name */
  1,   /* field[1] = persistent */
};
static const ProtobufCIntRange assign_interface_params__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor assign_interface_params__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "AssignInterfaceParams",
  "AssignInterfaceParams",
  "AssignInterfaceParams",
  "",
  sizeof(AssignInterfaceParams),
  2,
  assign_interface_params__field_descriptors,
  assign_interface_params__field_indices_by_name,
  1,  assign_interface_params__number_ranges,
  (ProtobufCMessageInit) assign_interface_params__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue controller_to_daemon__command__enum_values_by_number[27] =
{
  { "LIST_GUESTOS_CONFIGS", "CONTROLLER_TO_DAEMON__COMMAND__LIST_GUESTOS_CONFIGS", 1 },
  { "LIST_CONTAINERS", "CONTROLLER_TO_DAEMON__COMMAND__LIST_CONTAINERS", 2 },
  { "GET_CONTAINER_STATUS", "CONTROLLER_TO_DAEMON__COMMAND__GET_CONTAINER_STATUS", 3 },
  { "GET_CONTAINER_CONFIG", "CONTROLLER_TO_DAEMON__COMMAND__GET_CONTAINER_CONFIG", 4 },
  { "GET_LAST_LOG", "CONTROLLER_TO_DAEMON__COMMAND__GET_LAST_LOG", 5 },
  { "GET_CONTAINER_PID", "CONTROLLER_TO_DAEMON__COMMAND__GET_CONTAINER_PID", 6 },
  { "OBSERVE_STATUS_START", "CONTROLLER_TO_DAEMON__COMMAND__OBSERVE_STATUS_START", 10 },
  { "OBSERVE_STATUS_STOP", "CONTROLLER_TO_DAEMON__COMMAND__OBSERVE_STATUS_STOP", 11 },
  { "OBSERVE_LOG_START", "CONTROLLER_TO_DAEMON__COMMAND__OBSERVE_LOG_START", 14 },
  { "OBSERVE_LOG_STOP", "CONTROLLER_TO_DAEMON__COMMAND__OBSERVE_LOG_STOP", 15 },
  { "PUSH_GUESTOS_CONFIG", "CONTROLLER_TO_DAEMON__COMMAND__PUSH_GUESTOS_CONFIG", 20 },
  { "RELOAD_CONTAINERS", "CONTROLLER_TO_DAEMON__COMMAND__RELOAD_CONTAINERS", 21 },
  { "WIPE_DEVICE", "CONTROLLER_TO_DAEMON__COMMAND__WIPE_DEVICE", 30 },
  { "CONTAINER_START", "CONTROLLER_TO_DAEMON__COMMAND__CONTAINER_START", 101 },
  { "CONTAINER_STOP", "CONTROLLER_TO_DAEMON__COMMAND__CONTAINER_STOP", 102 },
  { "CONTAINER_SWITCH", "CONTROLLER_TO_DAEMON__COMMAND__CONTAINER_SWITCH", 103 },
  { "CONTAINER_FREEZE", "CONTROLLER_TO_DAEMON__COMMAND__CONTAINER_FREEZE", 104 },
  { "CONTAINER_UNFREEZE", "CONTROLLER_TO_DAEMON__COMMAND__CONTAINER_UNFREEZE", 105 },
  { "CONTAINER_WIPE", "CONTROLLER_TO_DAEMON__COMMAND__CONTAINER_WIPE", 106 },
  { "CONTAINER_SNAPSHOT", "CONTROLLER_TO_DAEMON__COMMAND__CONTAINER_SNAPSHOT", 107 },
  { "CONTAINER_ALLOWAUDIO", "CONTROLLER_TO_DAEMON__COMMAND__CONTAINER_ALLOWAUDIO", 108 },
  { "CONTAINER_DENYAUDIO", "CONTROLLER_TO_DAEMON__COMMAND__CONTAINER_DENYAUDIO", 109 },
  { "CONTAINER_ASSIGNIFACE", "CONTROLLER_TO_DAEMON__COMMAND__CONTAINER_ASSIGNIFACE", 110 },
  { "CONTAINER_UNASSIGNIFACE", "CONTROLLER_TO_DAEMON__COMMAND__CONTAINER_UNASSIGNIFACE", 111 },
  { "CONTAINER_LIST_IFACES", "CONTROLLER_TO_DAEMON__COMMAND__CONTAINER_LIST_IFACES", 112 },
  { "CONTAINER_EXEC_CMD", "CONTROLLER_TO_DAEMON__COMMAND__CONTAINER_EXEC_CMD", 113 },
  { "CONTAINER_EXEC_INPUT", "CONTROLLER_TO_DAEMON__COMMAND__CONTAINER_EXEC_INPUT", 114 },
};
static const ProtobufCIntRange controller_to_daemon__command__value_ranges[] = {
{1, 0},{10, 6},{14, 8},{20, 10},{30, 12},{101, 13},{0, 27}
};
static const ProtobufCEnumValueIndex controller_to_daemon__command__enum_values_by_name[27] =
{
  { "CONTAINER_ALLOWAUDIO", 20 },
  { "CONTAINER_ASSIGNIFACE", 22 },
  { "CONTAINER_DENYAUDIO", 21 },
  { "CONTAINER_EXEC_CMD", 25 },
  { "CONTAINER_EXEC_INPUT", 26 },
  { "CONTAINER_FREEZE", 16 },
  { "CONTAINER_LIST_IFACES", 24 },
  { "CONTAINER_SNAPSHOT", 19 },
  { "CONTAINER_START", 13 },
  { "CONTAINER_STOP", 14 },
  { "CONTAINER_SWITCH", 15 },
  { "CONTAINER_UNASSIGNIFACE", 23 },
  { "CONTAINER_UNFREEZE", 17 },
  { "CONTAINER_WIPE", 18 },
  { "GET_CONTAINER_CONFIG", 3 },
  { "GET_CONTAINER_PID", 5 },
  { "GET_CONTAINER_STATUS", 2 },
  { "GET_LAST_LOG", 4 },
  { "LIST_CONTAINERS", 1 },
  { "LIST_GUESTOS_CONFIGS", 0 },
  { "OBSERVE_LOG_START", 8 },
  { "OBSERVE_LOG_STOP", 9 },
  { "OBSERVE_STATUS_START", 6 },
  { "OBSERVE_STATUS_STOP", 7 },
  { "PUSH_GUESTOS_CONFIG", 10 },
  { "RELOAD_CONTAINERS", 11 },
  { "WIPE_DEVICE", 12 },
};
const ProtobufCEnumDescriptor controller_to_daemon__command__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ControllerToDaemon.Command",
  "Command",
  "ControllerToDaemon__Command",
  "",
  27,
  controller_to_daemon__command__enum_values_by_number,
  27,
  controller_to_daemon__command__enum_values_by_name,
  6,
  controller_to_daemon__command__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor controller_to_daemon__field_descriptors[10] =
{
  {
    "command",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(ControllerToDaemon, command),
    &controller_to_daemon__command__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "container_uuids",
    10,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(ControllerToDaemon, n_container_uuids),
    offsetof(ControllerToDaemon, container_uuids),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "container_start_params",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ControllerToDaemon, container_start_params),
    &container_start_params__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "assign_iface_params",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ControllerToDaemon, assign_iface_params),
    &assign_interface_params__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "exec_command",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ControllerToDaemon, exec_command),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "exec_args",
    14,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(ControllerToDaemon, n_exec_args),
    offsetof(ControllerToDaemon, exec_args),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "exec_input",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ControllerToDaemon, exec_input),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "guestos_config_file",
    20,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(ControllerToDaemon, has_guestos_config_file),
    offsetof(ControllerToDaemon, guestos_config_file),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "guestos_config_signature",
    21,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(ControllerToDaemon, has_guestos_config_signature),
    offsetof(ControllerToDaemon, guestos_config_signature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "guestos_config_certificate",
    22,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(ControllerToDaemon, has_guestos_config_certificate),
    offsetof(ControllerToDaemon, guestos_config_certificate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned controller_to_daemon__field_indices_by_name[] = {
  3,   /* field[3] = assign_iface_params */
  0,   /* field[0] = command */
  2,   /* field[2] = container_start_params */
  1,   /* field[1] = container_uuids */
  5,   /* field[5] = exec_args */
  4,   /* field[4] = exec_command */
  6,   /* field[6] = exec_input */
  9,   /* field[9] = guestos_config_certificate */
  7,   /* field[7] = guestos_config_file */
  8,   /* field[8] = guestos_config_signature */
};
static const ProtobufCIntRange controller_to_daemon__number_ranges[3 + 1] =
{
  { 1, 0 },
  { 10, 1 },
  { 20, 7 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor controller_to_daemon__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ControllerToDaemon",
  "ControllerToDaemon",
  "ControllerToDaemon",
  "",
  sizeof(ControllerToDaemon),
  10,
  controller_to_daemon__field_descriptors,
  controller_to_daemon__field_indices_by_name,
  3,  controller_to_daemon__number_ranges,
  (ProtobufCMessageInit) controller_to_daemon__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue daemon_to_controller__code__enum_values_by_number[13] =
{
  { "GUESTOS_CONFIGS_LIST", "DAEMON_TO_CONTROLLER__CODE__GUESTOS_CONFIGS_LIST", 1 },
  { "CONTAINERS_LIST", "DAEMON_TO_CONTROLLER__CODE__CONTAINERS_LIST", 2 },
  { "CONTAINER_STATUS", "DAEMON_TO_CONTROLLER__CODE__CONTAINER_STATUS", 3 },
  { "CONTAINER_CONFIG", "DAEMON_TO_CONTROLLER__CODE__CONTAINER_CONFIG", 4 },
  { "CONTAINER_IFACES", "DAEMON_TO_CONTROLLER__CODE__CONTAINER_IFACES", 5 },
  { "CONTAINER_PID", "DAEMON_TO_CONTROLLER__CODE__CONTAINER_PID", 6 },
  { "STATUS_CHANGED", "DAEMON_TO_CONTROLLER__CODE__STATUS_CHANGED", 10 },
  { "NOTIFICATION", "DAEMON_TO_CONTROLLER__CODE__NOTIFICATION", 11 },
  { "LOG_MESSAGE", "DAEMON_TO_CONTROLLER__CODE__LOG_MESSAGE", 12 },
  { "RESPONSE", "DAEMON_TO_CONTROLLER__CODE__RESPONSE", 13 },
  { "EXEC_END", "DAEMON_TO_CONTROLLER__CODE__EXEC_END", 14 },
  { "EXEC_OUTPUT", "DAEMON_TO_CONTROLLER__CODE__EXEC_OUTPUT", 15 },
  { "LOGON_DEVICE", "DAEMON_TO_CONTROLLER__CODE__LOGON_DEVICE", 200 },
};
static const ProtobufCIntRange daemon_to_controller__code__value_ranges[] = {
{1, 0},{10, 6},{200, 12},{0, 13}
};
static const ProtobufCEnumValueIndex daemon_to_controller__code__enum_values_by_name[13] =
{
  { "CONTAINERS_LIST", 1 },
  { "CONTAINER_CONFIG", 3 },
  { "CONTAINER_IFACES", 4 },
  { "CONTAINER_PID", 5 },
  { "CONTAINER_STATUS", 2 },
  { "EXEC_END", 10 },
  { "EXEC_OUTPUT", 11 },
  { "GUESTOS_CONFIGS_LIST", 0 },
  { "LOGON_DEVICE", 12 },
  { "LOG_MESSAGE", 8 },
  { "NOTIFICATION", 7 },
  { "RESPONSE", 9 },
  { "STATUS_CHANGED", 6 },
};
const ProtobufCEnumDescriptor daemon_to_controller__code__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "DaemonToController.Code",
  "Code",
  "DaemonToController__Code",
  "",
  13,
  daemon_to_controller__code__enum_values_by_number,
  13,
  daemon_to_controller__code__enum_values_by_name,
  3,
  daemon_to_controller__code__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue daemon_to_controller__response__enum_values_by_number[6] =
{
  { "CONTAINER_START_OK", "DAEMON_TO_CONTROLLER__RESPONSE__CONTAINER_START_OK", 1 },
  { "CONTAINER_START_LOCK_FAILED", "DAEMON_TO_CONTROLLER__RESPONSE__CONTAINER_START_LOCK_FAILED", 2 },
  { "CONTAINER_START_UNLOCK_FAILED", "DAEMON_TO_CONTROLLER__RESPONSE__CONTAINER_START_UNLOCK_FAILED", 3 },
  { "CONTAINER_START_PASSWD_WRONG", "DAEMON_TO_CONTROLLER__RESPONSE__CONTAINER_START_PASSWD_WRONG", 4 },
  { "CONTAINER_START_LOCKED_TILL_REBOOT", "DAEMON_TO_CONTROLLER__RESPONSE__CONTAINER_START_LOCKED_TILL_REBOOT", 5 },
  { "CONTAINER_START_EEXIST", "DAEMON_TO_CONTROLLER__RESPONSE__CONTAINER_START_EEXIST", 6 },
};
static const ProtobufCIntRange daemon_to_controller__response__value_ranges[] = {
{1, 0},{0, 6}
};
static const ProtobufCEnumValueIndex daemon_to_controller__response__enum_values_by_name[6] =
{
  { "CONTAINER_START_EEXIST", 5 },
  { "CONTAINER_START_LOCKED_TILL_REBOOT", 4 },
  { "CONTAINER_START_LOCK_FAILED", 1 },
  { "CONTAINER_START_OK", 0 },
  { "CONTAINER_START_PASSWD_WRONG", 3 },
  { "CONTAINER_START_UNLOCK_FAILED", 2 },
};
const ProtobufCEnumDescriptor daemon_to_controller__response__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "DaemonToController.Response",
  "Response",
  "DaemonToController__Response",
  "",
  6,
  daemon_to_controller__response__enum_values_by_number,
  6,
  daemon_to_controller__response__enum_values_by_name,
  1,
  daemon_to_controller__response__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor daemon_to_controller__field_descriptors[17] =
{
  {
    "code",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(DaemonToController, code),
    &daemon_to_controller__code__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "guestos_configs",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(DaemonToController, n_guestos_configs),
    offsetof(DaemonToController, guestos_configs),
    &guest_osconfig__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "container_uuids",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(DaemonToController, n_container_uuids),
    offsetof(DaemonToController, container_uuids),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "container_status",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(DaemonToController, n_container_status),
    offsetof(DaemonToController, container_status),
    &container_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "container_configs",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(DaemonToController, n_container_configs),
    offsetof(DaemonToController, container_configs),
    &container_config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "container_ifaces",
    9,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(DaemonToController, n_container_ifaces),
    offsetof(DaemonToController, container_ifaces),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "container_pid",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DaemonToController, has_container_pid),
    offsetof(DaemonToController, container_pid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "log_message",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DaemonToController, log_message),
    &log_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "response",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(DaemonToController, has_response),
    offsetof(DaemonToController, response),
    &daemon_to_controller__response__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device_uuid",
    200,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DaemonToController, device_uuid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "logon_hardware_name",
    201,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DaemonToController, logon_hardware_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "logon_hardware_serial",
    202,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DaemonToController, logon_hardware_serial),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "logon_imei",
    203,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DaemonToController, logon_imei),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "logon_mac_address",
    204,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DaemonToController, logon_mac_address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "logon_phone_number",
    205,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DaemonToController, logon_phone_number),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "exec_end_reason",
    206,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DaemonToController, exec_end_reason),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "exec_output",
    207,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DaemonToController, exec_output),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned daemon_to_controller__field_indices_by_name[] = {
  0,   /* field[0] = code */
  4,   /* field[4] = container_configs */
  5,   /* field[5] = container_ifaces */
  6,   /* field[6] = container_pid */
  3,   /* field[3] = container_status */
  2,   /* field[2] = container_uuids */
  9,   /* field[9] = device_uuid */
  15,   /* field[15] = exec_end_reason */
  16,   /* field[16] = exec_output */
  1,   /* field[1] = guestos_configs */
  7,   /* field[7] = log_message */
  10,   /* field[10] = logon_hardware_name */
  11,   /* field[11] = logon_hardware_serial */
  12,   /* field[12] = logon_imei */
  13,   /* field[13] = logon_mac_address */
  14,   /* field[14] = logon_phone_number */
  8,   /* field[8] = response */
};
static const ProtobufCIntRange daemon_to_controller__number_ranges[4 + 1] =
{
  { 1, 0 },
  { 5, 1 },
  { 12, 7 },
  { 200, 9 },
  { 0, 17 }
};
const ProtobufCMessageDescriptor daemon_to_controller__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DaemonToController",
  "DaemonToController",
  "DaemonToController",
  "",
  sizeof(DaemonToController),
  17,
  daemon_to_controller__field_descriptors,
  daemon_to_controller__field_indices_by_name,
  4,  daemon_to_controller__number_ranges,
  (ProtobufCMessageInit) daemon_to_controller__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue daemon_to_console__code__enum_values_by_number[2] =
{
  { "EXEC", "DAEMON_TO_CONSOLE__CODE__EXEC", 1 },
  { "INPUT", "DAEMON_TO_CONSOLE__CODE__INPUT", 2 },
};
static const ProtobufCIntRange daemon_to_console__code__value_ranges[] = {
{1, 0},{0, 2}
};
static const ProtobufCEnumValueIndex daemon_to_console__code__enum_values_by_name[2] =
{
  { "EXEC", 0 },
  { "INPUT", 1 },
};
const ProtobufCEnumDescriptor daemon_to_console__code__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "DaemonToConsole.Code",
  "Code",
  "DaemonToConsole__Code",
  "",
  2,
  daemon_to_console__code__enum_values_by_number,
  2,
  daemon_to_console__code__enum_values_by_name,
  1,
  daemon_to_console__code__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
char daemon_to_console__command__default_value[] = "/bin/sh";
char daemon_to_console__input__default_value[] = "";
static const ProtobufCFieldDescriptor daemon_to_console__field_descriptors[4] =
{
  {
    "code",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(DaemonToConsole, code),
    &daemon_to_console__code__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "command",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DaemonToConsole, command),
    NULL,
    &daemon_to_console__command__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "args",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(DaemonToConsole, n_args),
    offsetof(DaemonToConsole, args),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "input",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DaemonToConsole, input),
    NULL,
    &daemon_to_console__input__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned daemon_to_console__field_indices_by_name[] = {
  2,   /* field[2] = args */
  0,   /* field[0] = code */
  1,   /* field[1] = command */
  3,   /* field[3] = input */
};
static const ProtobufCIntRange daemon_to_console__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor daemon_to_console__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DaemonToConsole",
  "DaemonToConsole",
  "DaemonToConsole",
  "",
  sizeof(DaemonToConsole),
  4,
  daemon_to_console__field_descriptors,
  daemon_to_console__field_indices_by_name,
  1,  daemon_to_console__number_ranges,
  (ProtobufCMessageInit) daemon_to_console__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue console_to_daemon__code__enum_values_by_number[2] =
{
  { "EXEC_FAILURE", "CONSOLE_TO_DAEMON__CODE__EXEC_FAILURE", 1 },
  { "EXEC_SUCCESS", "CONSOLE_TO_DAEMON__CODE__EXEC_SUCCESS", 2 },
};
static const ProtobufCIntRange console_to_daemon__code__value_ranges[] = {
{1, 0},{0, 2}
};
static const ProtobufCEnumValueIndex console_to_daemon__code__enum_values_by_name[2] =
{
  { "EXEC_FAILURE", 0 },
  { "EXEC_SUCCESS", 1 },
};
const ProtobufCEnumDescriptor console_to_daemon__code__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ConsoleToDaemon.Code",
  "Code",
  "ConsoleToDaemon__Code",
  "",
  2,
  console_to_daemon__code__enum_values_by_number,
  2,
  console_to_daemon__code__enum_values_by_name,
  1,
  console_to_daemon__code__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const uint32_t console_to_daemon__pid__default_value = 0u;
static const ProtobufCFieldDescriptor console_to_daemon__field_descriptors[2] =
{
  {
    "code",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(ConsoleToDaemon, code),
    &console_to_daemon__code__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pid",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ConsoleToDaemon, pid),
    NULL,
    &console_to_daemon__pid__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned console_to_daemon__field_indices_by_name[] = {
  0,   /* field[0] = code */
  1,   /* field[1] = pid */
};
static const ProtobufCIntRange console_to_daemon__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor console_to_daemon__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ConsoleToDaemon",
  "ConsoleToDaemon",
  "ConsoleToDaemon",
  "",
  sizeof(ConsoleToDaemon),
  2,
  console_to_daemon__field_descriptors,
  console_to_daemon__field_indices_by_name,
  1,  console_to_daemon__number_ranges,
  (ProtobufCMessageInit) console_to_daemon__init,
  NULL,NULL,NULL    /* reserved[123] */
};
