/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: container.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "container.pb-c.h"
void   container_image_size__init
                     (ContainerImageSize         *message)
{
  static ContainerImageSize init_value = CONTAINER_IMAGE_SIZE__INIT;
  *message = init_value;
}
size_t container_image_size__get_packed_size
                     (const ContainerImageSize *message)
{
  assert(message->base.descriptor == &container_image_size__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t container_image_size__pack
                     (const ContainerImageSize *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &container_image_size__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t container_image_size__pack_to_buffer
                     (const ContainerImageSize *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &container_image_size__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ContainerImageSize *
       container_image_size__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ContainerImageSize *)
     protobuf_c_message_unpack (&container_image_size__descriptor,
                                allocator, len, data);
}
void   container_image_size__free_unpacked
                     (ContainerImageSize *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &container_image_size__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   container_config__init
                     (ContainerConfig         *message)
{
  static ContainerConfig init_value = CONTAINER_CONFIG__INIT;
  *message = init_value;
}
size_t container_config__get_packed_size
                     (const ContainerConfig *message)
{
  assert(message->base.descriptor == &container_config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t container_config__pack
                     (const ContainerConfig *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &container_config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t container_config__pack_to_buffer
                     (const ContainerConfig *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &container_config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ContainerConfig *
       container_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ContainerConfig *)
     protobuf_c_message_unpack (&container_config__descriptor,
                                allocator, len, data);
}
void   container_config__free_unpacked
                     (ContainerConfig *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &container_config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   container_status__init
                     (ContainerStatus         *message)
{
  static ContainerStatus init_value = CONTAINER_STATUS__INIT;
  *message = init_value;
}
size_t container_status__get_packed_size
                     (const ContainerStatus *message)
{
  assert(message->base.descriptor == &container_status__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t container_status__pack
                     (const ContainerStatus *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &container_status__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t container_status__pack_to_buffer
                     (const ContainerStatus *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &container_status__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ContainerStatus *
       container_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ContainerStatus *)
     protobuf_c_message_unpack (&container_status__descriptor,
                                allocator, len, data);
}
void   container_status__free_unpacked
                     (ContainerStatus *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &container_status__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor container_image_size__field_descriptors[3] =
{
  {
    "image_name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ContainerImageSize, image_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "image_size",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(ContainerImageSize, image_size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "image_file",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ContainerImageSize, image_file),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned container_image_size__field_indices_by_name[] = {
  2,   /* field[2] = image_file */
  0,   /* field[0] = image_name */
  1,   /* field[1] = image_size */
};
static const ProtobufCIntRange container_image_size__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor container_image_size__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ContainerImageSize",
  "ContainerImageSize",
  "ContainerImageSize",
  "",
  sizeof(ContainerImageSize),
  3,
  container_image_size__field_descriptors,
  container_image_size__field_indices_by_name,
  1,  container_image_size__number_ranges,
  (ProtobufCMessageInit) container_image_size__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const uint32_t container_config__ram_limit__default_value = 1024u;
static const ContainerType container_config__type__default_value = CONTAINER_TYPE__CONTAINER;
static const protobuf_c_boolean container_config__allow_autostart__default_value = 0;
static const protobuf_c_boolean container_config__netns__default_value = 1;
static const ProtobufCFieldDescriptor container_config__field_descriptors[14] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ContainerConfig, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "guest_os",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ContainerConfig, guest_os),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "guestos_version",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(ContainerConfig, has_guestos_version),
    offsetof(ContainerConfig, guestos_version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "image_sizes",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ContainerConfig, n_image_sizes),
    offsetof(ContainerConfig, image_sizes),
    &container_image_size__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ram_limit",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ContainerConfig, has_ram_limit),
    offsetof(ContainerConfig, ram_limit),
    NULL,
    &container_config__ram_limit__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "color",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(ContainerConfig, color),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(ContainerConfig, type),
    &container_type__descriptor,
    &container_config__type__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "allow_autostart",
    17,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(ContainerConfig, has_allow_autostart),
    offsetof(ContainerConfig, allow_autostart),
    NULL,
    &container_config__allow_autostart__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "feature_enabled",
    20,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(ContainerConfig, n_feature_enabled),
    offsetof(ContainerConfig, feature_enabled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dns_server",
    21,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ContainerConfig, dns_server),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "netns",
    22,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(ContainerConfig, has_netns),
    offsetof(ContainerConfig, netns),
    NULL,
    &container_config__netns__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "net_ifaces",
    23,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(ContainerConfig, n_net_ifaces),
    offsetof(ContainerConfig, net_ifaces),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "allow_dev",
    25,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(ContainerConfig, n_allow_dev),
    offsetof(ContainerConfig, allow_dev),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "assign_dev",
    26,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(ContainerConfig, n_assign_dev),
    offsetof(ContainerConfig, assign_dev),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned container_config__field_indices_by_name[] = {
  7,   /* field[7] = allow_autostart */
  12,   /* field[12] = allow_dev */
  13,   /* field[13] = assign_dev */
  5,   /* field[5] = color */
  9,   /* field[9] = dns_server */
  8,   /* field[8] = feature_enabled */
  1,   /* field[1] = guest_os */
  2,   /* field[2] = guestos_version */
  3,   /* field[3] = image_sizes */
  0,   /* field[0] = name */
  11,   /* field[11] = net_ifaces */
  10,   /* field[10] = netns */
  4,   /* field[4] = ram_limit */
  6,   /* field[6] = type */
};
static const ProtobufCIntRange container_config__number_ranges[4 + 1] =
{
  { 1, 0 },
  { 17, 7 },
  { 20, 8 },
  { 25, 12 },
  { 0, 14 }
};
const ProtobufCMessageDescriptor container_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ContainerConfig",
  "ContainerConfig",
  "ContainerConfig",
  "",
  sizeof(ContainerConfig),
  14,
  container_config__field_descriptors,
  container_config__field_indices_by_name,
  4,  container_config__number_ranges,
  (ProtobufCMessageInit) container_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor container_status__field_descriptors[6] =
{
  {
    "uuid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ContainerStatus, uuid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ContainerStatus, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(ContainerStatus, type),
    &container_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "state",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(ContainerStatus, state),
    &container_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uptime",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(ContainerStatus, uptime),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "created",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(ContainerStatus, created),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned container_status__field_indices_by_name[] = {
  5,   /* field[5] = created */
  1,   /* field[1] = name */
  3,   /* field[3] = state */
  2,   /* field[2] = type */
  4,   /* field[4] = uptime */
  0,   /* field[0] = uuid */
};
static const ProtobufCIntRange container_status__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor container_status__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ContainerStatus",
  "ContainerStatus",
  "ContainerStatus",
  "",
  sizeof(ContainerStatus),
  6,
  container_status__field_descriptors,
  container_status__field_indices_by_name,
  1,  container_status__number_ranges,
  (ProtobufCMessageInit) container_status__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue container_type__enum_values_by_number[2] =
{
  { "CONTAINER", "CONTAINER_TYPE__CONTAINER", 1 },
  { "KVM", "CONTAINER_TYPE__KVM", 2 },
};
static const ProtobufCIntRange container_type__value_ranges[] = {
{1, 0},{0, 2}
};
static const ProtobufCEnumValueIndex container_type__enum_values_by_name[2] =
{
  { "CONTAINER", 0 },
  { "KVM", 1 },
};
const ProtobufCEnumDescriptor container_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ContainerType",
  "ContainerType",
  "ContainerType",
  "",
  2,
  container_type__enum_values_by_number,
  2,
  container_type__enum_values_by_name,
  1,
  container_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue container_state__enum_values_by_number[9] =
{
  { "STOPPED", "CONTAINER_STATE__STOPPED", 1 },
  { "STARTING", "CONTAINER_STATE__STARTING", 2 },
  { "BOOTING", "CONTAINER_STATE__BOOTING", 3 },
  { "RUNNING", "CONTAINER_STATE__RUNNING", 4 },
  { "FREEZING", "CONTAINER_STATE__FREEZING", 5 },
  { "FROZEN", "CONTAINER_STATE__FROZEN", 6 },
  { "ZOMBIE", "CONTAINER_STATE__ZOMBIE", 7 },
  { "SHUTDOWN", "CONTAINER_STATE__SHUTDOWN", 8 },
  { "SETUP", "CONTAINER_STATE__SETUP", 9 },
};
static const ProtobufCIntRange container_state__value_ranges[] = {
{1, 0},{0, 9}
};
static const ProtobufCEnumValueIndex container_state__enum_values_by_name[9] =
{
  { "BOOTING", 2 },
  { "FREEZING", 4 },
  { "FROZEN", 5 },
  { "RUNNING", 3 },
  { "SETUP", 8 },
  { "SHUTDOWN", 7 },
  { "STARTING", 1 },
  { "STOPPED", 0 },
  { "ZOMBIE", 6 },
};
const ProtobufCEnumDescriptor container_state__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ContainerState",
  "ContainerState",
  "ContainerState",
  "",
  9,
  container_state__enum_values_by_number,
  9,
  container_state__enum_values_by_name,
  1,
  container_state__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue container_connectivity__enum_values_by_number[4] =
{
  { "OFFLINE", "CONTAINER_CONNECTIVITY__OFFLINE", 1 },
  { "MOBILE_ONLY", "CONTAINER_CONNECTIVITY__MOBILE_ONLY", 2 },
  { "WIFI_ONLY", "CONTAINER_CONNECTIVITY__WIFI_ONLY", 3 },
  { "MOBILE_AND_WIFI", "CONTAINER_CONNECTIVITY__MOBILE_AND_WIFI", 4 },
};
static const ProtobufCIntRange container_connectivity__value_ranges[] = {
{1, 0},{0, 4}
};
static const ProtobufCEnumValueIndex container_connectivity__enum_values_by_name[4] =
{
  { "MOBILE_AND_WIFI", 3 },
  { "MOBILE_ONLY", 1 },
  { "OFFLINE", 0 },
  { "WIFI_ONLY", 2 },
};
const ProtobufCEnumDescriptor container_connectivity__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ContainerConnectivity",
  "ContainerConnectivity",
  "ContainerConnectivity",
  "",
  4,
  container_connectivity__enum_values_by_number,
  4,
  container_connectivity__enum_values_by_name,
  1,
  container_connectivity__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
