/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: device.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "device.pb-c.h"
void   device_config__init
                     (DeviceConfig         *message)
{
  static DeviceConfig init_value = DEVICE_CONFIG__INIT;
  *message = init_value;
}
size_t device_config__get_packed_size
                     (const DeviceConfig *message)
{
  assert(message->base.descriptor == &device_config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t device_config__pack
                     (const DeviceConfig *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &device_config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t device_config__pack_to_buffer
                     (const DeviceConfig *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &device_config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DeviceConfig *
       device_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DeviceConfig *)
     protobuf_c_message_unpack (&device_config__descriptor,
                                allocator, len, data);
}
void   device_config__free_unpacked
                     (DeviceConfig *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &device_config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
char device_config__c0os__default_value[] = "a0os";
char device_config__host_addr__default_value[] = "";
char device_config__host_if__default_value[] = "wlan0";
char device_config__host_gateway__default_value[] = "";
char device_config__host_dns__default_value[] = "";
static const protobuf_c_boolean device_config__should_led_blink__default_value = 0;
static const uint32_t device_config__host_subnet__default_value = 0u;
static const ProtobufCFieldDescriptor device_config__field_descriptors[12] =
{
  {
    "uuid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DeviceConfig, uuid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mdm_node",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DeviceConfig, mdm_node),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mdm_service",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DeviceConfig, mdm_service),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "telephony_uuid",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DeviceConfig, telephony_uuid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "update_base_url",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DeviceConfig, update_base_url),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "should_led_blink",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(DeviceConfig, has_should_led_blink),
    offsetof(DeviceConfig, should_led_blink),
    NULL,
    &device_config__should_led_blink__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "c0os",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DeviceConfig, c0os),
    NULL,
    &device_config__c0os__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "host_addr",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DeviceConfig, host_addr),
    NULL,
    &device_config__host_addr__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "host_subnet",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DeviceConfig, has_host_subnet),
    offsetof(DeviceConfig, host_subnet),
    NULL,
    &device_config__host_subnet__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "host_if",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DeviceConfig, host_if),
    NULL,
    &device_config__host_if__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "host_gateway",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DeviceConfig, host_gateway),
    NULL,
    &device_config__host_gateway__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "host_dns",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DeviceConfig, host_dns),
    NULL,
    &device_config__host_dns__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned device_config__field_indices_by_name[] = {
  6,   /* field[6] = c0os */
  7,   /* field[7] = host_addr */
  11,   /* field[11] = host_dns */
  10,   /* field[10] = host_gateway */
  9,   /* field[9] = host_if */
  8,   /* field[8] = host_subnet */
  1,   /* field[1] = mdm_node */
  2,   /* field[2] = mdm_service */
  5,   /* field[5] = should_led_blink */
  3,   /* field[3] = telephony_uuid */
  4,   /* field[4] = update_base_url */
  0,   /* field[0] = uuid */
};
static const ProtobufCIntRange device_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 12 }
};
const ProtobufCMessageDescriptor device_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DeviceConfig",
  "DeviceConfig",
  "DeviceConfig",
  "",
  sizeof(DeviceConfig),
  12,
  device_config__field_descriptors,
  device_config__field_indices_by_name,
  1,  device_config__number_ranges,
  (ProtobufCMessageInit) device_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
