/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: guestos.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "guestos.pb-c.h"
void   i18_nstring__init
                     (I18NString         *message)
{
  static I18NString init_value = I18_NSTRING__INIT;
  *message = init_value;
}
size_t i18_nstring__get_packed_size
                     (const I18NString *message)
{
  assert(message->base.descriptor == &i18_nstring__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t i18_nstring__pack
                     (const I18NString *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &i18_nstring__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t i18_nstring__pack_to_buffer
                     (const I18NString *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &i18_nstring__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
I18NString *
       i18_nstring__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (I18NString *)
     protobuf_c_message_unpack (&i18_nstring__descriptor,
                                allocator, len, data);
}
void   i18_nstring__free_unpacked
                     (I18NString *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &i18_nstring__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   guest_osmount__init
                     (GuestOSMount         *message)
{
  static GuestOSMount init_value = GUEST_OSMOUNT__INIT;
  *message = init_value;
}
size_t guest_osmount__get_packed_size
                     (const GuestOSMount *message)
{
  assert(message->base.descriptor == &guest_osmount__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t guest_osmount__pack
                     (const GuestOSMount *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &guest_osmount__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t guest_osmount__pack_to_buffer
                     (const GuestOSMount *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &guest_osmount__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GuestOSMount *
       guest_osmount__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GuestOSMount *)
     protobuf_c_message_unpack (&guest_osmount__descriptor,
                                allocator, len, data);
}
void   guest_osmount__free_unpacked
                     (GuestOSMount *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &guest_osmount__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   guest_osconfig__init
                     (GuestOSConfig         *message)
{
  static GuestOSConfig init_value = GUEST_OSCONFIG__INIT;
  *message = init_value;
}
size_t guest_osconfig__get_packed_size
                     (const GuestOSConfig *message)
{
  assert(message->base.descriptor == &guest_osconfig__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t guest_osconfig__pack
                     (const GuestOSConfig *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &guest_osconfig__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t guest_osconfig__pack_to_buffer
                     (const GuestOSConfig *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &guest_osconfig__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GuestOSConfig *
       guest_osconfig__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GuestOSConfig *)
     protobuf_c_message_unpack (&guest_osconfig__descriptor,
                                allocator, len, data);
}
void   guest_osconfig__free_unpacked
                     (GuestOSConfig *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &guest_osconfig__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor i18_nstring__field_descriptors[3] =
{
  {
    "en",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(I18NString, en),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "de",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(I18NString, de),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fr",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(I18NString, fr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned i18_nstring__field_indices_by_name[] = {
  1,   /* field[1] = de */
  0,   /* field[0] = en */
  2,   /* field[2] = fr */
};
static const ProtobufCIntRange i18_nstring__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor i18_nstring__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "I18NString",
  "I18NString",
  "I18NString",
  "",
  sizeof(I18NString),
  3,
  i18_nstring__field_descriptors,
  i18_nstring__field_indices_by_name,
  1,  i18_nstring__number_ranges,
  (ProtobufCMessageInit) i18_nstring__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue guest_osmount__type__enum_values_by_number[10] =
{
  { "SHARED", "GUEST_OSMOUNT__TYPE__SHARED", 1 },
  { "DEVICE", "GUEST_OSMOUNT__TYPE__DEVICE", 2 },
  { "DEVICE_RW", "GUEST_OSMOUNT__TYPE__DEVICE_RW", 3 },
  { "EMPTY", "GUEST_OSMOUNT__TYPE__EMPTY", 4 },
  { "COPY", "GUEST_OSMOUNT__TYPE__COPY", 5 },
  { "FLASH", "GUEST_OSMOUNT__TYPE__FLASH", 6 },
  { "SHARED_DATA", "GUEST_OSMOUNT__TYPE__SHARED_DATA", 7 },
  { "OVERLAY_RO", "GUEST_OSMOUNT__TYPE__OVERLAY_RO", 8 },
  { "SHARED_RW", "GUEST_OSMOUNT__TYPE__SHARED_RW", 9 },
  { "OVERLAY_RW", "GUEST_OSMOUNT__TYPE__OVERLAY_RW", 10 },
};
static const ProtobufCIntRange guest_osmount__type__value_ranges[] = {
{1, 0},{0, 10}
};
static const ProtobufCEnumValueIndex guest_osmount__type__enum_values_by_name[10] =
{
  { "COPY", 4 },
  { "DEVICE", 1 },
  { "DEVICE_RW", 2 },
  { "EMPTY", 3 },
  { "FLASH", 5 },
  { "OVERLAY_RO", 7 },
  { "OVERLAY_RW", 9 },
  { "SHARED", 0 },
  { "SHARED_DATA", 6 },
  { "SHARED_RW", 8 },
};
const ProtobufCEnumDescriptor guest_osmount__type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "GuestOSMount.Type",
  "Type",
  "GuestOSMount__Type",
  "",
  10,
  guest_osmount__type__enum_values_by_number,
  10,
  guest_osmount__type__enum_values_by_name,
  1,
  guest_osmount__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const uint32_t guest_osmount__min_size__default_value = 10u;
static const uint32_t guest_osmount__max_size__default_value = 16384u;
static const uint32_t guest_osmount__def_size__default_value = 1024u;
static const ProtobufCFieldDescriptor guest_osmount__field_descriptors[12] =
{
  {
    "image_file",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(GuestOSMount, image_file),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mount_point",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(GuestOSMount, mount_point),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fs_type",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(GuestOSMount, fs_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mount_type",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(GuestOSMount, mount_type),
    &guest_osmount__type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "min_size",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(GuestOSMount, has_min_size),
    offsetof(GuestOSMount, min_size),
    NULL,
    &guest_osmount__min_size__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "max_size",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(GuestOSMount, has_max_size),
    offsetof(GuestOSMount, max_size),
    NULL,
    &guest_osmount__max_size__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "def_size",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(GuestOSMount, has_def_size),
    offsetof(GuestOSMount, def_size),
    NULL,
    &guest_osmount__def_size__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "image_size",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(GuestOSMount, has_image_size),
    offsetof(GuestOSMount, image_size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "image_sha1",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(GuestOSMount, image_sha1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "image_sha2_256",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(GuestOSMount, image_sha2_256),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mount_data",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(GuestOSMount, mount_data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data_size",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(GuestOSMount, has_data_size),
    offsetof(GuestOSMount, data_size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned guest_osmount__field_indices_by_name[] = {
  11,   /* field[11] = data_size */
  6,   /* field[6] = def_size */
  2,   /* field[2] = fs_type */
  0,   /* field[0] = image_file */
  8,   /* field[8] = image_sha1 */
  9,   /* field[9] = image_sha2_256 */
  7,   /* field[7] = image_size */
  5,   /* field[5] = max_size */
  4,   /* field[4] = min_size */
  10,   /* field[10] = mount_data */
  1,   /* field[1] = mount_point */
  3,   /* field[3] = mount_type */
};
static const ProtobufCIntRange guest_osmount__number_ranges[3 + 1] =
{
  { 1, 0 },
  { 6, 4 },
  { 10, 7 },
  { 0, 12 }
};
const ProtobufCMessageDescriptor guest_osmount__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GuestOSMount",
  "GuestOSMount",
  "GuestOSMount",
  "",
  sizeof(GuestOSMount),
  12,
  guest_osmount__field_descriptors,
  guest_osmount__field_indices_by_name,
  3,  guest_osmount__number_ranges,
  (ProtobufCMessageInit) guest_osmount__init,
  NULL,NULL,NULL    /* reserved[123] */
};
char guest_osconfig__init_path__default_value[] = "/init";
static const protobuf_c_boolean guest_osconfig__feature_phone__default_value = 0;
static const protobuf_c_boolean guest_osconfig__feature_bluetooth__default_value = 0;
static const protobuf_c_boolean guest_osconfig__feature_wifi__default_value = 0;
static const protobuf_c_boolean guest_osconfig__feature_mobile_data__default_value = 0;
static const protobuf_c_boolean guest_osconfig__feature_sensors__default_value = 0;
static const protobuf_c_boolean guest_osconfig__feature_camera__default_value = 0;
static const protobuf_c_boolean guest_osconfig__feature_audio__default_value = 0;
static const protobuf_c_boolean guest_osconfig__feature_bg_booting__default_value = 0;
static const protobuf_c_boolean guest_osconfig__feature_vpn__default_value = 0;
static const protobuf_c_boolean guest_osconfig__feature_devtmpfs__default_value = 0;
static const uint32_t guest_osconfig__min_ram_limit__default_value = 128u;
static const uint32_t guest_osconfig__def_ram_limit__default_value = 1024u;
static const ProtobufCFieldDescriptor guest_osconfig__field_descriptors[25] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(GuestOSConfig, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hardware",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(GuestOSConfig, hardware),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "version",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(GuestOSConfig, version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mounts",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(GuestOSConfig, n_mounts),
    offsetof(GuestOSConfig, mounts),
    &guest_osmount__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "init_path",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(GuestOSConfig, init_path),
    NULL,
    &guest_osconfig__init_path__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "init_param",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(GuestOSConfig, n_init_param),
    offsetof(GuestOSConfig, init_param),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "init_env",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(GuestOSConfig, n_init_env),
    offsetof(GuestOSConfig, init_env),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mounts_setup",
    9,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(GuestOSConfig, n_mounts_setup),
    offsetof(GuestOSConfig, mounts_setup),
    &guest_osmount__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "description",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(GuestOSConfig, description),
    &i18_nstring__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "description_long",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(GuestOSConfig, description_long),
    &i18_nstring__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "upstream_version",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(GuestOSConfig, upstream_version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "icon",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(GuestOSConfig, has_icon),
    offsetof(GuestOSConfig, icon),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "build_date",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(GuestOSConfig, build_date),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "feature_phone",
    20,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(GuestOSConfig, has_feature_phone),
    offsetof(GuestOSConfig, feature_phone),
    NULL,
    &guest_osconfig__feature_phone__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "feature_bluetooth",
    21,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(GuestOSConfig, has_feature_bluetooth),
    offsetof(GuestOSConfig, feature_bluetooth),
    NULL,
    &guest_osconfig__feature_bluetooth__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "feature_wifi",
    22,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(GuestOSConfig, has_feature_wifi),
    offsetof(GuestOSConfig, feature_wifi),
    NULL,
    &guest_osconfig__feature_wifi__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "feature_mobile_data",
    23,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(GuestOSConfig, has_feature_mobile_data),
    offsetof(GuestOSConfig, feature_mobile_data),
    NULL,
    &guest_osconfig__feature_mobile_data__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "feature_sensors",
    24,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(GuestOSConfig, has_feature_sensors),
    offsetof(GuestOSConfig, feature_sensors),
    NULL,
    &guest_osconfig__feature_sensors__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "feature_camera",
    25,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(GuestOSConfig, has_feature_camera),
    offsetof(GuestOSConfig, feature_camera),
    NULL,
    &guest_osconfig__feature_camera__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "feature_audio",
    26,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(GuestOSConfig, has_feature_audio),
    offsetof(GuestOSConfig, feature_audio),
    NULL,
    &guest_osconfig__feature_audio__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "feature_bg_booting",
    27,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(GuestOSConfig, has_feature_bg_booting),
    offsetof(GuestOSConfig, feature_bg_booting),
    NULL,
    &guest_osconfig__feature_bg_booting__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "feature_vpn",
    28,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(GuestOSConfig, has_feature_vpn),
    offsetof(GuestOSConfig, feature_vpn),
    NULL,
    &guest_osconfig__feature_vpn__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "feature_devtmpfs",
    29,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(GuestOSConfig, has_feature_devtmpfs),
    offsetof(GuestOSConfig, feature_devtmpfs),
    NULL,
    &guest_osconfig__feature_devtmpfs__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "min_ram_limit",
    30,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(GuestOSConfig, has_min_ram_limit),
    offsetof(GuestOSConfig, min_ram_limit),
    NULL,
    &guest_osconfig__min_ram_limit__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "def_ram_limit",
    32,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(GuestOSConfig, has_def_ram_limit),
    offsetof(GuestOSConfig, def_ram_limit),
    NULL,
    &guest_osconfig__def_ram_limit__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned guest_osconfig__field_indices_by_name[] = {
  12,   /* field[12] = build_date */
  24,   /* field[24] = def_ram_limit */
  8,   /* field[8] = description */
  9,   /* field[9] = description_long */
  19,   /* field[19] = feature_audio */
  20,   /* field[20] = feature_bg_booting */
  14,   /* field[14] = feature_bluetooth */
  18,   /* field[18] = feature_camera */
  22,   /* field[22] = feature_devtmpfs */
  16,   /* field[16] = feature_mobile_data */
  13,   /* field[13] = feature_phone */
  17,   /* field[17] = feature_sensors */
  21,   /* field[21] = feature_vpn */
  15,   /* field[15] = feature_wifi */
  1,   /* field[1] = hardware */
  11,   /* field[11] = icon */
  6,   /* field[6] = init_env */
  5,   /* field[5] = init_param */
  4,   /* field[4] = init_path */
  23,   /* field[23] = min_ram_limit */
  3,   /* field[3] = mounts */
  7,   /* field[7] = mounts_setup */
  0,   /* field[0] = name */
  10,   /* field[10] = upstream_version */
  2,   /* field[2] = version */
};
static const ProtobufCIntRange guest_osconfig__number_ranges[4 + 1] =
{
  { 1, 0 },
  { 5, 3 },
  { 20, 13 },
  { 32, 24 },
  { 0, 25 }
};
const ProtobufCMessageDescriptor guest_osconfig__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GuestOSConfig",
  "GuestOSConfig",
  "GuestOSConfig",
  "",
  sizeof(GuestOSConfig),
  25,
  guest_osconfig__field_descriptors,
  guest_osconfig__field_indices_by_name,
  4,  guest_osconfig__number_ranges,
  (ProtobufCMessageInit) guest_osconfig__init,
  NULL,NULL,NULL    /* reserved[123] */
};
