/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: tpm2d.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "tpm2d.pb-c.h"
void   pcr__init
                     (Pcr         *message)
{
  static Pcr init_value = PCR__INIT;
  *message = init_value;
}
size_t pcr__get_packed_size
                     (const Pcr *message)
{
  assert(message->base.descriptor == &pcr__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pcr__pack
                     (const Pcr *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pcr__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pcr__pack_to_buffer
                     (const Pcr *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pcr__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Pcr *
       pcr__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Pcr *)
     protobuf_c_message_unpack (&pcr__descriptor,
                                allocator, len, data);
}
void   pcr__free_unpacked
                     (Pcr *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &pcr__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   controller_to_tpm__init
                     (ControllerToTpm         *message)
{
  static ControllerToTpm init_value = CONTROLLER_TO_TPM__INIT;
  *message = init_value;
}
size_t controller_to_tpm__get_packed_size
                     (const ControllerToTpm *message)
{
  assert(message->base.descriptor == &controller_to_tpm__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t controller_to_tpm__pack
                     (const ControllerToTpm *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &controller_to_tpm__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t controller_to_tpm__pack_to_buffer
                     (const ControllerToTpm *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &controller_to_tpm__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ControllerToTpm *
       controller_to_tpm__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ControllerToTpm *)
     protobuf_c_message_unpack (&controller_to_tpm__descriptor,
                                allocator, len, data);
}
void   controller_to_tpm__free_unpacked
                     (ControllerToTpm *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &controller_to_tpm__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tpm_to_controller__init
                     (TpmToController         *message)
{
  static TpmToController init_value = TPM_TO_CONTROLLER__INIT;
  *message = init_value;
}
size_t tpm_to_controller__get_packed_size
                     (const TpmToController *message)
{
  assert(message->base.descriptor == &tpm_to_controller__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tpm_to_controller__pack
                     (const TpmToController *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tpm_to_controller__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tpm_to_controller__pack_to_buffer
                     (const TpmToController *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tpm_to_controller__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TpmToController *
       tpm_to_controller__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TpmToController *)
     protobuf_c_message_unpack (&tpm_to_controller__descriptor,
                                allocator, len, data);
}
void   tpm_to_controller__free_unpacked
                     (TpmToController *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &tpm_to_controller__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor pcr__field_descriptors[2] =
{
  {
    "number",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Pcr, has_number),
    offsetof(Pcr, number),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Pcr, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pcr__field_indices_by_name[] = {
  0,   /* field[0] = number */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange pcr__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor pcr__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Pcr",
  "Pcr",
  "Pcr",
  "",
  sizeof(Pcr),
  2,
  pcr__field_descriptors,
  pcr__field_indices_by_name,
  1,  pcr__number_ranges,
  (ProtobufCMessageInit) pcr__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue controller_to_tpm__code__enum_values_by_number[9] =
{
  { "INTERNAL_ATTESTATION_REQ", "CONTROLLER_TO_TPM__CODE__INTERNAL_ATTESTATION_REQ", 1 },
  { "DMCRYPT_SETUP", "CONTROLLER_TO_TPM__CODE__DMCRYPT_SETUP", 2 },
  { "EXIT", "CONTROLLER_TO_TPM__CODE__EXIT", 3 },
  { "RANDOM_REQ", "CONTROLLER_TO_TPM__CODE__RANDOM_REQ", 4 },
  { "CLEAR", "CONTROLLER_TO_TPM__CODE__CLEAR", 5 },
  { "DMCRYPT_LOCK", "CONTROLLER_TO_TPM__CODE__DMCRYPT_LOCK", 6 },
  { "CHANGE_OWNER_PWD", "CONTROLLER_TO_TPM__CODE__CHANGE_OWNER_PWD", 7 },
  { "DMCRYPT_RESET", "CONTROLLER_TO_TPM__CODE__DMCRYPT_RESET", 8 },
  { "ML_APPEND", "CONTROLLER_TO_TPM__CODE__ML_APPEND", 9 },
};
static const ProtobufCIntRange controller_to_tpm__code__value_ranges[] = {
{1, 0},{0, 9}
};
static const ProtobufCEnumValueIndex controller_to_tpm__code__enum_values_by_name[9] =
{
  { "CHANGE_OWNER_PWD", 6 },
  { "CLEAR", 4 },
  { "DMCRYPT_LOCK", 5 },
  { "DMCRYPT_RESET", 7 },
  { "DMCRYPT_SETUP", 1 },
  { "EXIT", 2 },
  { "INTERNAL_ATTESTATION_REQ", 0 },
  { "ML_APPEND", 8 },
  { "RANDOM_REQ", 3 },
};
const ProtobufCEnumDescriptor controller_to_tpm__code__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ControllerToTpm.Code",
  "Code",
  "ControllerToTpm__Code",
  "",
  9,
  controller_to_tpm__code__enum_values_by_number,
  9,
  controller_to_tpm__code__enum_values_by_name,
  1,
  controller_to_tpm__code__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const IdsAttestationType controller_to_tpm__atype__default_value = IDS_ATTESTATION_TYPE__BASIC;
static const ProtobufCFieldDescriptor controller_to_tpm__field_descriptors[11] =
{
  {
    "code",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(ControllerToTpm, code),
    &controller_to_tpm__code__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "atype",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(ControllerToTpm, has_atype),
    offsetof(ControllerToTpm, atype),
    &ids_attestation_type__descriptor,
    &controller_to_tpm__atype__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "qualifyingData",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ControllerToTpm, qualifyingdata),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pcrs",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ControllerToTpm, has_pcrs),
    offsetof(ControllerToTpm, pcrs),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dmcrypt_device",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ControllerToTpm, dmcrypt_device),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "password",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ControllerToTpm, password),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rand_size",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ControllerToTpm, has_rand_size),
    offsetof(ControllerToTpm, rand_size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "password_new",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ControllerToTpm, password_new),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ml_filename",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ControllerToTpm, ml_filename),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ml_datahash",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(ControllerToTpm, has_ml_datahash),
    offsetof(ControllerToTpm, ml_datahash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ml_hashalg",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(ControllerToTpm, has_ml_hashalg),
    offsetof(ControllerToTpm, ml_hashalg),
    &hash_alg_len__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned controller_to_tpm__field_indices_by_name[] = {
  1,   /* field[1] = atype */
  0,   /* field[0] = code */
  4,   /* field[4] = dmcrypt_device */
  9,   /* field[9] = ml_datahash */
  8,   /* field[8] = ml_filename */
  10,   /* field[10] = ml_hashalg */
  5,   /* field[5] = password */
  7,   /* field[7] = password_new */
  3,   /* field[3] = pcrs */
  2,   /* field[2] = qualifyingData */
  6,   /* field[6] = rand_size */
};
static const ProtobufCIntRange controller_to_tpm__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor controller_to_tpm__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ControllerToTpm",
  "ControllerToTpm",
  "ControllerToTpm",
  "",
  sizeof(ControllerToTpm),
  11,
  controller_to_tpm__field_descriptors,
  controller_to_tpm__field_indices_by_name,
  1,  controller_to_tpm__number_ranges,
  (ProtobufCMessageInit) controller_to_tpm__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue tpm_to_controller__code__enum_values_by_number[4] =
{
  { "INTERNAL_ATTESTATION_RES", "TPM_TO_CONTROLLER__CODE__INTERNAL_ATTESTATION_RES", 1 },
  { "GENERIC_RESPONSE", "TPM_TO_CONTROLLER__CODE__GENERIC_RESPONSE", 2 },
  { "FDE_RESPONSE", "TPM_TO_CONTROLLER__CODE__FDE_RESPONSE", 3 },
  { "RANDOM_RESPONSE", "TPM_TO_CONTROLLER__CODE__RANDOM_RESPONSE", 4 },
};
static const ProtobufCIntRange tpm_to_controller__code__value_ranges[] = {
{1, 0},{0, 4}
};
static const ProtobufCEnumValueIndex tpm_to_controller__code__enum_values_by_name[4] =
{
  { "FDE_RESPONSE", 2 },
  { "GENERIC_RESPONSE", 1 },
  { "INTERNAL_ATTESTATION_RES", 0 },
  { "RANDOM_RESPONSE", 3 },
};
const ProtobufCEnumDescriptor tpm_to_controller__code__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "TpmToController.Code",
  "Code",
  "TpmToController__Code",
  "",
  4,
  tpm_to_controller__code__enum_values_by_number,
  4,
  tpm_to_controller__code__enum_values_by_name,
  1,
  tpm_to_controller__code__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue tpm_to_controller__generic_response__enum_values_by_number[2] =
{
  { "CMD_OK", "TPM_TO_CONTROLLER__GENERIC_RESPONSE__CMD_OK", 1 },
  { "CMD_FAILED", "TPM_TO_CONTROLLER__GENERIC_RESPONSE__CMD_FAILED", 2 },
};
static const ProtobufCIntRange tpm_to_controller__generic_response__value_ranges[] = {
{1, 0},{0, 2}
};
static const ProtobufCEnumValueIndex tpm_to_controller__generic_response__enum_values_by_name[2] =
{
  { "CMD_FAILED", 1 },
  { "CMD_OK", 0 },
};
const ProtobufCEnumDescriptor tpm_to_controller__generic_response__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "TpmToController.GenericResponse",
  "GenericResponse",
  "TpmToController__GenericResponse",
  "",
  2,
  tpm_to_controller__generic_response__enum_values_by_number,
  2,
  tpm_to_controller__generic_response__enum_values_by_name,
  1,
  tpm_to_controller__generic_response__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue tpm_to_controller__fde_response__enum_values_by_number[7] =
{
  { "FDE_OK", "TPM_TO_CONTROLLER__FDE_RESPONSE__FDE_OK", 1 },
  { "FDE_AUTH_FAILED", "TPM_TO_CONTROLLER__FDE_RESPONSE__FDE_AUTH_FAILED", 2 },
  { "FDE_KEYGEN_FAILED", "TPM_TO_CONTROLLER__FDE_RESPONSE__FDE_KEYGEN_FAILED", 3 },
  { "FDE_NO_DEVICE", "TPM_TO_CONTROLLER__FDE_RESPONSE__FDE_NO_DEVICE", 4 },
  { "FDE_KEY_ACCESS_LOCKED", "TPM_TO_CONTROLLER__FDE_RESPONSE__FDE_KEY_ACCESS_LOCKED", 5 },
  { "FDE_RESET", "TPM_TO_CONTROLLER__FDE_RESPONSE__FDE_RESET", 6 },
  { "FDE_UNEXPECTED_ERROR", "TPM_TO_CONTROLLER__FDE_RESPONSE__FDE_UNEXPECTED_ERROR", 7 },
};
static const ProtobufCIntRange tpm_to_controller__fde_response__value_ranges[] = {
{1, 0},{0, 7}
};
static const ProtobufCEnumValueIndex tpm_to_controller__fde_response__enum_values_by_name[7] =
{
  { "FDE_AUTH_FAILED", 1 },
  { "FDE_KEYGEN_FAILED", 2 },
  { "FDE_KEY_ACCESS_LOCKED", 4 },
  { "FDE_NO_DEVICE", 3 },
  { "FDE_OK", 0 },
  { "FDE_RESET", 5 },
  { "FDE_UNEXPECTED_ERROR", 6 },
};
const ProtobufCEnumDescriptor tpm_to_controller__fde_response__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "TpmToController.FdeResponse",
  "FdeResponse",
  "TpmToController__FdeResponse",
  "",
  7,
  tpm_to_controller__fde_response__enum_values_by_number,
  7,
  tpm_to_controller__fde_response__enum_values_by_name,
  1,
  tpm_to_controller__fde_response__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const IdsAttestationType tpm_to_controller__atype__default_value = IDS_ATTESTATION_TYPE__BASIC;
static const ProtobufCFieldDescriptor tpm_to_controller__field_descriptors[11] =
{
  {
    "code",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(TpmToController, code),
    &tpm_to_controller__code__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "atype",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(TpmToController, has_atype),
    offsetof(TpmToController, atype),
    &ids_attestation_type__descriptor,
    &tpm_to_controller__atype__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "halg",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TpmToController, halg),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "quoted",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TpmToController, quoted),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "signature",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TpmToController, signature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pcr_values",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(TpmToController, n_pcr_values),
    offsetof(TpmToController, pcr_values),
    &pcr__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "certificate_uri",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TpmToController, certificate_uri),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "response",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(TpmToController, has_response),
    offsetof(TpmToController, response),
    &tpm_to_controller__generic_response__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fde_response",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(TpmToController, has_fde_response),
    offsetof(TpmToController, fde_response),
    &tpm_to_controller__fde_response__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rand_data",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TpmToController, rand_data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ml_entry",
    11,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(TpmToController, n_ml_entry),
    offsetof(TpmToController, ml_entry),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tpm_to_controller__field_indices_by_name[] = {
  1,   /* field[1] = atype */
  6,   /* field[6] = certificate_uri */
  0,   /* field[0] = code */
  8,   /* field[8] = fde_response */
  2,   /* field[2] = halg */
  10,   /* field[10] = ml_entry */
  5,   /* field[5] = pcr_values */
  3,   /* field[3] = quoted */
  9,   /* field[9] = rand_data */
  7,   /* field[7] = response */
  4,   /* field[4] = signature */
};
static const ProtobufCIntRange tpm_to_controller__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor tpm_to_controller__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "TpmToController",
  "TpmToController",
  "TpmToController",
  "",
  sizeof(TpmToController),
  11,
  tpm_to_controller__field_descriptors,
  tpm_to_controller__field_indices_by_name,
  1,  tpm_to_controller__number_ranges,
  (ProtobufCMessageInit) tpm_to_controller__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue ids_attestation_type__enum_values_by_number[3] =
{
  { "BASIC", "IDS_ATTESTATION_TYPE__BASIC", 0 },
  { "ALL", "IDS_ATTESTATION_TYPE__ALL", 1 },
  { "ADVANCED", "IDS_ATTESTATION_TYPE__ADVANCED", 2 },
};
static const ProtobufCIntRange ids_attestation_type__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex ids_attestation_type__enum_values_by_name[3] =
{
  { "ADVANCED", 2 },
  { "ALL", 1 },
  { "BASIC", 0 },
};
const ProtobufCEnumDescriptor ids_attestation_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "IdsAttestationType",
  "IdsAttestationType",
  "IdsAttestationType",
  "",
  3,
  ids_attestation_type__enum_values_by_number,
  3,
  ids_attestation_type__enum_values_by_name,
  1,
  ids_attestation_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue hash_alg_len__enum_values_by_number[3] =
{
  { "SHA1", "HASH_ALG_LEN__SHA1", 20 },
  { "SHA256", "HASH_ALG_LEN__SHA256", 32 },
  { "SHA384", "HASH_ALG_LEN__SHA384", 48 },
};
static const ProtobufCIntRange hash_alg_len__value_ranges[] = {
{20, 0},{32, 1},{48, 2},{0, 3}
};
static const ProtobufCEnumValueIndex hash_alg_len__enum_values_by_name[3] =
{
  { "SHA1", 0 },
  { "SHA256", 1 },
  { "SHA384", 2 },
};
const ProtobufCEnumDescriptor hash_alg_len__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "HashAlgLen",
  "HashAlgLen",
  "HashAlgLen",
  "",
  3,
  hash_alg_len__enum_values_by_number,
  3,
  hash_alg_len__enum_values_by_name,
  3,
  hash_alg_len__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
