/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: logf.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "logf.pb-c.h"
void   log_message__init
                     (LogMessage         *message)
{
  static LogMessage init_value = LOG_MESSAGE__INIT;
  *message = init_value;
}
size_t log_message__get_packed_size
                     (const LogMessage *message)
{
  assert(message->base.descriptor == &log_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t log_message__pack
                     (const LogMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &log_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t log_message__pack_to_buffer
                     (const LogMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &log_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LogMessage *
       log_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LogMessage *)
     protobuf_c_message_unpack (&log_message__descriptor,
                                allocator, len, data);
}
void   log_message__free_unpacked
                     (LogMessage *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &log_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor log_message__field_descriptors[2] =
{
  {
    "prio",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(LogMessage, prio),
    &log_priority__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msg",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(LogMessage, msg),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned log_message__field_indices_by_name[] = {
  1,   /* field[1] = msg */
  0,   /* field[0] = prio */
};
static const ProtobufCIntRange log_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor log_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "LogMessage",
  "LogMessage",
  "LogMessage",
  "",
  sizeof(LogMessage),
  2,
  log_message__field_descriptors,
  log_message__field_indices_by_name,
  1,  log_message__number_ranges,
  (ProtobufCMessageInit) log_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue log_priority__enum_values_by_number[7] =
{
  { "TRACE", "LOG_PRIORITY__TRACE", 1 },
  { "DEBUG", "LOG_PRIORITY__DEBUG", 2 },
  { "INFO", "LOG_PRIORITY__INFO", 3 },
  { "WARN", "LOG_PRIORITY__WARN", 4 },
  { "ERROR", "LOG_PRIORITY__ERROR", 5 },
  { "FATAL", "LOG_PRIORITY__FATAL", 6 },
  { "SILENT", "LOG_PRIORITY__SILENT", 7 },
};
static const ProtobufCIntRange log_priority__value_ranges[] = {
{1, 0},{0, 7}
};
static const ProtobufCEnumValueIndex log_priority__enum_values_by_name[7] =
{
  { "DEBUG", 1 },
  { "ERROR", 4 },
  { "FATAL", 5 },
  { "INFO", 2 },
  { "SILENT", 6 },
  { "TRACE", 0 },
  { "WARN", 3 },
};
const ProtobufCEnumDescriptor log_priority__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "LogPriority",
  "LogPriority",
  "LogPriority",
  "",
  7,
  log_priority__enum_values_by_number,
  7,
  log_priority__enum_values_by_name,
  1,
  log_priority__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
